name: Android CI (APK)
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: android-actions/setup-android@v3
      - run: yes | sdkmanager --licenses
      - run: sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"
      - uses: gradle/actions/setup-gradle@v4
        with: { cache-read-only: false }
      - name: Ensure wrapper
        run: |
          if [ ! -x "./gradlew" ]; then
            curl -sLo gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q gradle-8.7-bin.zip
            ./gradle-8.7/bin/gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew
      - name: Build APK
        run: ./gradlew --stacktrace --info --no-daemon :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: one-stop-debug-apk-v1.1.5
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
